function Home() {
    return (  <>
    <span>1</span>
    <span>2</span>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    <div>This is home page</div>
    </>);
}

export default Home;